### ISSUE TITLE
Support `chacha20-poly1305@openssh.com`

### ISSUE THREAD

**Issue by veehaitch** [scottcwang/openssh_key_parser#2]
I'm dealing with SSH keys which use `chacha20-poly1305@openssh.com` as a cipher. Currently, only `aes256-ctr` is supported.

```bash
ssh-keygen -t 'ed25519' -Z 'chacha20-poly1305@openssh.com' -a 64 -C "" -N "test1234" -f id_ed25519
```

Any chance to add support for `chacha20-poly1305@openssh.com`? Thanks!

**Comment by scottcwang** [comment]
Definitely! Supporting more ciphers is precisely what I'm working on now.

Just a heads up that if you are currently coding to the `Cipher` classes, that class's API is about to change. (This is because my original design of passing only the `KDF` result to the `Cipher` was quite terrible.) Then all I'd need to do is wire all of the cipher types, including `chacha20-poly1305@openssh.com`, up to the `cryptography` backend.

**Comment by scottcwang** [comment]
@veehaitch - I just uploaded version 0.0.4, which supports `chacha20-poly1305@openssh.com`. Let me know how it goes!

**Comment by veehaitch** [comment]
Yes, works like a charm. Thanks for implementing support so quickly!
